### ISSUE TITLE
App closing itself

### ISSUE THREAD

**Issue by BedrockDev** [berict/Tapad#115]
App kills itself after the splash screen.

**Comment by BedrockDev** [comment]
wait does this issue is on v2.3?

**Comment by jaxinator555** [comment]
The issue is gone in the latest Alpha release as of 16-06-2017

**Comment by BedrockDev** [comment]
Probably fixed

**Comment by BedrockDev** [comment]
Crashes on @Gennadiyev 's device. needs check

**Comment by BedrockDev** [comment]
Fixed
