### ISSUE TITLE
App restarts after manually removing corrupted preset

### ISSUE THREAD

**Issue by jaxinator555** [berict/Tapad#120]
The app restarts itself after manually removing a corrupted preset.

**Comment by jaxinator555** [comment]
This problem does not persist if the preset is not corrupted.

**Comment by BedrockDev** [comment]
Hmm this needs fix

**Comment by BedrockDev** [comment]
@jaxinator555 Please specify how to replicate this error. Tried to do so, it didn't crash.

**Comment by jaxinator555** [comment]
The problem does not persist. It is gone in the latest alpha I think.
