### ISSUE TITLE
Start page option

### ISSUE THREAD

**Issue by jaxinator555** [berict/Tapad#123]
This is a standard feature right now, but it feels more natural if you go back to the start screen if you press the back button now, because that is where you come from if you set a preset.

**Comment by BedrockDev** [comment]
Please specify the screen. There is a double press back button to close already in the app.

**Comment by jaxinator555** [comment]
When I set a preset to play, it goes to the next screen, the launchpad. It feels more natural if you go back to the preset selection screen when you press the back button. It adds to the overal usability and flow of the app if this is implemented. It is still a good thing to press the back button twice before going back.

**Comment by BedrockDev** [comment]
Are you talking about the 2.3 alpha 2? It doesn't move to other screen after selecting a preset.

**Comment by BedrockDev** [comment]
Options should contain
- Last played preset
- Preset store

**Comment by BedrockDev** [comment]
closed via #168
