### ISSUE TITLE
Action bar menu glitched

### ISSUE THREAD

**Issue by Gennadiyev** [berict/Tapad#132]

**Comment by BedrockDev** [comment]
Will be fixed

**Comment by BedrockDev** [comment]
Can't replicate the issue. Please let me know your API info @Gennadiyev

**Comment by BedrockDev** [comment]
[Glitched image](https://images.discordapp.net/attachments/325269374984388609/329626506894508033/Screenshot_2017-06-28-22-15-32.jpeg?width=516&height=918)

**Comment by BedrockDev** [comment]
probably a device-specific error, reopen this if this occurs in two or more devices
