### ISSUE TITLE
Message input doesn't wrap

### ISSUE THREAD

**Issue by Gennadiyev** [berict/Tapad#137]
when editing bug report and feedback in-app, and i write a long message or with many lines, the input block can't be slid up or down.
Though IME can solve the editing issue, reviewing the message can be real hard.

**Comment by BedrockDev** [comment]
![screenshot_20170626-061203](https://user-images.githubusercontent.com/13298429/27519780-702ab04a-5a36-11e7-97e2-4a55c7bf16fb.png)
Issue checked, will be fixed

**Comment by Gennadiyev** [comment]
Uh, i mean the input block bug report and feedback..

**Comment by BedrockDev** [comment]
Those are already available for scrolling, what do you mean?
