### ISSUE TITLE
Preset not loaded after put at directory

### ISSUE THREAD

**Issue by Gennadiyev** [berict/Tapad#144]
Tapad should load it automatically, or have a choice to refresh preset list.

**Comment by BedrockDev** [comment]
It doesn't show at the installed tab on preset store?

**Comment by BedrockDev** [comment]
On v2.3-alpha.4, you need to set the folder name to preset name

For faded, try `alan_walker_faded_gesture`

**Comment by Gennadiyev** [comment]
trying

**Comment by BedrockDev** [comment]
Open preset feature will be available
