### ISSUE TITLE
App crashes on opening preset store

### ISSUE THREAD

**Issue by Gennadiyev** [berict/Tapad#145]

**Comment by BedrockDev** [comment]
Ah rip

**Comment by BedrockDev** [comment]
Will check
An issue in ResourcesEx.java line 716 has occurred in Tapad Android: https://fabric.io/studio-berict/android/apps/com.bedrock.padder/issues/59589005be077a4dccea1cf5

**Comment by BedrockDev** [comment]
Fixed with #146
