### ISSUE TITLE
Reload preset store

### ISSUE THREAD

**Issue by Gennadiyev** [berict/Tapad#147]
slide down on preset store should refresh preset store.

**Comment by BedrockDev** [comment]
actually it refreshes on every swipe, so idk if this is needed

**Comment by Gennadiyev** [comment]
ok that makes that unnecessary. And i guess the presets are not that quickly updated...

**Comment by BedrockDev** [comment]
after changing network connections after can't connect to the preset store

**Comment by BedrockDev** [comment]
reopen this when problem related to this issue occurs
