### ISSUE TITLE
Touch effects not disappearing

### ISSUE THREAD

**Issue by Gennadiyev** [berict/Tapad#38]
When  sliding the finger from a sound pad (in the 4x4 area) to a control pad (deck & light), the light will not stop.

**Comment by BedrockDev** [comment]
@Gennadiyev please let me know how to replicate this bug, can't find this bug on my testing

**Comment by Gennadiyev** [comment]
Uh just noticed the mention. lol can't duplicate cuz iths crashing now..

**Comment by BedrockDev** [comment]
Don't know this is still an issue after update with #149

**Comment by BedrockDev** [comment]
Reopen this when occur
