### ISSUE TITLE
Use light icons for toolbar icons

### ISSUE THREAD

**Issue by BedrockDev** [berict/Tapad#63]
Icons should match the title color

**Comment by Gennadiyev** [comment]
A bit too fancy?

**Comment by BedrockDev** [comment]
`Light` icons mean not the real *light*, it means `white` colors

**Comment by BedrockDev** [comment]
Btw this should be dynamically change by the preset `primaryColor`, but it's too complicated for now

**Comment by BedrockDev** [comment]
closed for now
