### ISSUE TITLE
Preset store / Preset creator

### ISSUE THREAD

**Issue by BedrockDev** [berict/Tapad#82]
Make a zip file that contains all of the information of the preset

> makes the preset shareable and downloadable

**Comment by BedrockDev** [comment]
https://stackoverflow.com/questions/9324103/download-and-extract-zip-file-in-android

**Comment by BedrockDev** [comment]
https://developer.android.com/training/basics/data-storage/files.html

**Comment by Gennadiyev** [comment]
Zip files should contain
- Song_name.zip
  - meta.txt
  - deck 1
    -1.1Normal
    -...
  - deck 2
    ...
  -deck 3
    ...
  -deck 4
    ...
  -tutorial.txt
  -explore.txt

**Comment by BedrockDev** [comment]
Should create preset folder structure as well

**Comment by BedrockDev** [comment]
Make a cross platform ***Preset maker*** kind of software

**Comment by BedrockDev** [comment]
- ***file_name.zip***
  - *sounds*
    - ***[nametag]\_[deck]\_[pad]\_[gesture].wav***
    - ...
  - *timing*
    - ***[pad]\_[gesture].txt***
    - `this is global timing, doesn't get affected by decks`
      - timing in `milliseconds`
  - *about*
    - ***album_art.jpg***
    - ***artist_icon.png***
      - `this should contain transparent background`
    - ***artist_image.jpg***
      - `this should contain image of the artist \(artist profile picture\)`
    - ***about_json.txt***

**Comment by BedrockDev** [comment]
the ***Preset maker*** software could be web-based html

**Comment by BedrockDev** [comment]
need to open the preset from zip [High priority]

**Comment by BedrockDev** [comment]
done
